-- Inserir usuário admin padrão
INSERT INTO employees (
    id,
    name,
    surname,
    birth_date,
    cpf,
    email,
    phone,
    password,
    role,
    cep,
    street,
    neighborhood,
    number,
    city,
    uf,
    state,
    complement,
    active,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'Admin',
    'Sistema',
    '1990-01-01',
    '12345678901',
    'admin@empresa.com',
    '11999999999',
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- admin123
    'ADMIN',
    '01234567',
    'Rua Admin',
    'Centro',
    '123',
    'São Paulo',
    'SP',
    'São Paulo',
    'Sala 1',
    true,
    NOW(),
    NOW()
) ON CONFLICT (email) DO NOTHING;
